### PR TITLE
Update Sublime highlighting for selected actions

### PR DESCRIPTION
**Pull request by celtic-coder**
As noted in https://github.com/cpsolver/Dashrep-language/issues/19

### CODE REVIEW

**Review by cpsolver — CHANGES_REQUESTED** [review]
Liam, thanks for finding and fixing this inconsistency.  Based on looking at the file changes, below are more actions that currently have the wrong kind of highlighting.  Would you mind fixing these?  I don't know how to edit a file that has changes that aren't yet merged.  Thanks!

yes-or-no-same-two-words
yes-or-no-opposite
yes-if-all-yes
yes-if-any-yes
no-if-any-no
yes-if-not-no
no-if-not-yes
numeric-add
numeric-multiply
numeric-maximum
numeric-minimum

**Comment by celtic-coder** [comment]
[comment]: # (https://github.com/cpsolver/Dashrep-language/pull/20)

Hi Richard (@cpsolver),

I have made the suggested changes. I have taken the liberty to also move the following two phrases:

- numeric-pi
- numeric-map-tile-zoom

Please let me know if these are correct or if any other further changes are required.

Kind Regards,
Liam

**Comment by cpsolver** [comment]
Oops, the descriptions of "numeric-pi" and "numeric-map-tile-zoom" refer to these as "actions" but actually they should be documented as "phrases."  So they should not be moved to the list of actions.

The mistake is in the file "specifications_phrase_descriptions".  If you have time to fix that file by changing the word "action" to "phrase" for those two items, I'd appreciate it.  (I'm staying too busy clearing up misunderstandings about ranked choice voting prior to the November election.)

FWIW, the phrase "numeric-pi" is pre-assigned a definition of the number pi.  (Code: "$global_pi = 4.0 * atan2( 1.0 , 1.0 ) ; $global_dashrep_replacement{ 'numeric<character_hyphen>pi' } = sprintf( "%f" , $global_pi ) ;").

FWIW, the phrase "numeric-map-tile-zoom" is a parameter/value used by the action "numeric-y-map-tile-number-based-on-latitude".  It seldom changes between each use of this action.  That's why (simpler, faster) I didn't supply it as a parameter to that action.

**Comment by celtic-coder** [comment]
Hi Richard (@cpsolver),

I have updated the descriptions for the following two phrases and also reverted the change in the Sublime Text syntax:

- numeric-pi
- numeric-map-tile-zoom

Please let me know if any further changes are required.

Kind Regards,
Liam

**Pull request merged**
