### PR TITLE
Update testing code

### PR DESCRIPTION
**Pull request by celtic-coder**
Hi Richard (@cpsolver),

The pull request updates "handle-one-check-for-correct-value.txt" by replacing older values (such as "*---" for "combee", for example).

Please ignore if the testing code already handles deprecated values.

Kind Regards,
Liam

### CODE REVIEW

**Comment by cpsolver** [comment]
Liam, thank you for your assistance!!!

On the surface your changes look like they will work -- and are long overdue.

Yet I'm a fan of testing and not just assuming that what looks good is actually going to work correctly.

I'm new to using Git and Github to collaborate.  So it will take time for me to learn how to accept your pull request, download it, and test it.

Plus, I need to get the NewsHereNow.com website working again to fully test your pull request.  (That's the final test.)  I'm in the process of migrating that site to a new web hosting package, and it's taking much longer than expected to do the full migration.

If your change does not pass testing, the change might involve complexity beyond surface appearances.  We might need to break it up into a separate Dashrep action that expands a template into a Dashrep phrase, and then use that separate Dashrep phrase within the higher-level template.  That's because sometimes I've found that combining one Dashrep template phrase with another Dashrep template phrase doesn't work like I intended.

Liam, I greatly appreciate what you're doing to help refine the Dashrep language!  Thank you!

Richard Fobes
The VoteFair guy
Author of "The Creative Problem Solver's Toolbox"

**Comment by celtic-coder** [comment]
[comment]: # (https://github.com/cpsolver/Dashrep-language/pull/8)

Hi Richard (@cpsolver),

You are more than welcome! I was setting up a new Windows 10 machine and noticed that I had some updates that I had researched months ago, but had not submitted to your repo. 

While working on this PR, I also noticed that the __\*---__ syntax also appears on the Dashrep.Org homepage. I have submitted a Pull Request (https://github.com/cpsolver/Dashrep-language/pull/9) to replace this syntax. Again, feel free to ignore the suggested changes if they do not pass testing.

Kind Regards,
Liam

**Review by cpsolver — APPROVED** [review]
Approving pull request

**Comment by celtic-coder** [comment]
[comment]: # (https://github.com/cpsolver/Dashrep-language/pull/8)

Hi Richard (@cpsolver),

Thanks for looking into the pull requests!

However, when I check the pull requests that are closed (either this one or for example, https://github.com/cpsolver/Dashrep-language/pull/11), I see the following message about **Closed with unmerged commits**:
 
closed-with-unmerged-commits

The commits have been approved, and the pull request is closed, but the commits have not been merged into the "master" branch of the repo. 

**_Completing the merge of a Pull Request involves two steps:_**

1. **Click the green "Merge pull request" button:**

merge-pull-request-button-initial

This is the step that you have already completed.

2. **Click the green "Confirm merge" button:**

confirm-merge-button

Typically, this is what immediately appears once the "Merge pull request" button has been clicked. However, it can be easily missed, especially on a mobile device with a small screen. This has happened to me in the past.

However, if the pull request has been closed, a "Reopen pull request" button is available at the bottom of the screen:

Reopen-pull-request-button

This will then return you to Step 1 (The green "Merge pull request" button). Once Step 2 is completed, then a message like the following will appear (with the purple "merged" icon):

merged-commit-message

An excellent resource for learning about branches, commits and merges is GitHub's own **"[Introduction to GitHub](https://github.com/skills/introduction-to-github)"** repo. The README file on the main page has the instructions on how to start. It should take about 15 to 30 minutes to complete the lesson. It was a helpful reminder to me on the proper way of doing things.

Kind Regards,
Liam

**Pull request merged**
